### ISSUE TITLE
We could conduct our entire Coders Cooperative via Github if we wanted to.

### ISSUE THREAD

**Issue by mikeputnam** [appletonmakerspace/helloworld#7]
Thoughts?

**Comment by raver1975** [comment]
There is a lot of value in meeting in person. And some of us didn't get the whole github tutorial. ;)

**Comment by zo0o0ot** [comment]
It'd certainly make it easier to participate if you weren't able to come in on Mondays.  I think it's a "why not both?" instead of an either/or.

**Comment by mikeputnam** [comment]
Ah yes. Wasn't insinuating that we trade in-person for social/internet; rather augment it.

The majority of open source project contributors never meet each other.

My suggestion was more of a push to be able to progress asynchronously via internet in addition to weekly via real life.

**Comment by mikeputnam** [comment]
Also more at replacing the administrivia/communication bits I've setup (Google docs, etc)

**Comment by gegere** [comment]
:+1:

**Comment by mikeputnam** [comment]
Closing this as we now leave at least a stub markdown file over in the https://github.com/appletonmakerspace/coder_cooperative_talks repo for each topic.
